version: '3'
services:
  geth:
    container_name: "geth"
    build: ./geth
    volumes:
      - ./geth:/geth
    ports:
      - '30303:30303'
      - '8545:8545'
      - '8546:8546'
    command: >
      - sh