version: '3'
services:
  watcher:
    container_name: "watcher"
    build: ./watcher
    volumes:
      - ./watcher:/work
      - ./watcher/src/voices:/usr/share/hts-voice/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /run/user/1000/pulse/native:/pulse/native
      - $HOME/.config/pulse/cookie:/pulse/cookie
      - ./watcher/conf/client.conf:/root/.config/pulse/client.conf
      - ./watcher/conf/default.pa:/root/.pulse/default.pa
    command: python3 watch.py
    #network_mode: host
    environment:
      - DISPLAY=:0.0
      - PULSE_SERVER=/pulse/native
      - PULSE_COOKIE=/pulse/cookie
    # devices:
    #   - /dev/snd:/dev/snd
    privileged: true
    depends_on:
      - geth

  geth:
    container_name: "geth"
    build: ./geth
    volumes:
      - ./geth:/geth
    ports:
      - '30303:30303'
      - '8545:8545'
      - '8546:8546'
    command: >
      geth --datadir /geth/data --syncmode fast --port 30303
      --http --http.addr '0.0.0.0' --http.corsdomain '*'
      --http.vhosts '*' --http.port 8545 --http.api 'personal,eth,net,web3'
      --ws --ws.addr "0.0.0.0" --ws.api 'eth,web3,personal,net'
      --ws.origins '*' --ws.port 8546
      --networkid 32414 --miner.gasprice '0' --unlock 0 --nousb
      --password /geth/data/password.txt
      --allow-insecure-unlock --nodiscover

  nginx:
    container_name: "nginx"
    build: ./nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    ports:
      - '80:80'
    depends_on:
      - watcher
      - geth
